USE moneykids;
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (1, "돈을 저축하는 이유는?", "미래를 준비하기 위해", "미래의 필요를 대비할 수 있습니다.", "초급");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (2, "가격이 오를 때 사는 것이 좋은가요?", "아니오", "낮을 때 사서 높을 때 파는 것이 이득입니다.", "중급");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (3, "장난감, 옷, 음식처럼 손으로 만질 수 있는 물건은 재화라고 불러요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (4, "희소성이란, 모든 사람이 원하는 만큼 물건을 충분히 가질 수 있는 것을 말해요.", "X", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (5, "우리는 물건을 선택할 때, 하나를 고르면 다른 것은 포기해야 할 때가 있어요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (6, "재화는 눈에 보이지 않거나, 손으로 만질 수 없는 감정이나 느낌을 말해요.", "X", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (7, "경제를 배우면 물건을 선택할 때 도움을 받을 수 있어요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (8, "기회비용은 포기한 것 중에서 가장 가치 있는 것을 말해요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (9, "천 원으로 공책, 과자, 볼펜을 모두 살 수 있으면 기회비용이 생겨요.", "X", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (10, "시간도 기회비용이 될 수 있어요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (11, "서로 필요한 물건을 바꾸는 것을 교환이라고 해요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (12, "특화란 각자 잘하는 것에 집중하는 걸 말해요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (13, "나라끼리 물건을 사고파는 것을 무역이라고 해요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (14, "무역을 하면 원하는 물건을 더 비싸게 사게 돼요.", "X", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (15, "편의점이나 인터넷 쇼핑몰도 시장이라고 할 수 있어요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (16, "서비스시장은 물건을 사지 않고 파는 곳만 해당돼요.", "X", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (17, "영화관이나 병원은 서비스시장이라고 할 수 있어요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (18, "시장은 경제와는 상관이 없는 곳이에요.", "X", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (19, "시장에서는 물건과 서비스를 사고팔 수 있어요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (20, "사고 싶은 사람이 많으면 물건의 가격이 올라갈 수 있어요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (21, "똑같은 물건이 많이 생기면 물건 가격이 올라가요.", "X", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (22, "사고 싶은 사람과 팔고 싶은 사람이 얼마나 많은지에 따라서 가격이 달라져요.", "O", NULL, "1");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (23, "가격은 항상 변하지 않고 똑같아요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (24, "사람들이 많이 사고 싶어 하면 가격은 올라가요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (25, "가게나 기업은 물건을 팔기 위해 서로 경쟁해요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (26, "경쟁이 없으면 값싸고 좋은 물건이 더 많이 나올 수 있어요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (27, "경쟁은 소비자가 더 좋은 물건을 고르는 데 도움을 줘요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (28, "기업이 새로운 기술을 개발하는 것은 경쟁과는 상관이 없어요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (29, "경쟁은 나라의 경제가 발전하는 것에도 도움이 될 수 있어요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (30, "합리적인 소비란 필요한 것을 골라서 쓰는 것이에요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (31, "필요한 것을 골라 쓰는 것보다 아무거나 사는 것이 나아요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (32, "용돈기입장은 돈이 어디서 들어오고 나가는지 알 수 있도록 도와줘요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (33, "무조건 돈을 아끼는 것이 합리적인 소비예요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (34, "소비는 우리가 필요한 것을 사는 행동이에요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (35, "저축은 돈을 모으는 것이에요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (36, "저축한 돈은 아무 쓸모가 없어요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (37, "은행에 돈을 맡기면 이자를 받을 수 있어요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (38, "이자는 돈을 빌린 사람이 받는 것이에요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (39, "저축은 개인과 사회 모두에게 도움이 돼요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (40, "은행은 대표적인 금융기관이에요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (41, "금융기관은 돈을 빌려주는 일을 하지 않아요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (42, "돈을 맡긴 사람은 금융기관에서 이자를 받을 수 있어요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (43, "금융기관은 기업이 물건을 만들도록 도와줘요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (44, "금융기관은 돈을 빌리고 맡기는 곳이에요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (45, "신용이란 돈을 잘 갚을 수 있는 믿음을 말해요.", "O", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (46, "신용이 낮으면 돈을 빌리기 쉬워요.", "X", NULL, "2");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (47, "신용카드는 나중에 갚는 방식이에요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (48, "신용이 좋으면 카드나 돈을 더 쉽게 쓸 수 있어요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (49, "자기 능력보다 많이 쓰는 것이 신용관리에 좋아요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (50, "기업은 사람을 고용하고 물건을 만들어 경제에 기여해요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (51, "기업은 나라 경제와는 관계가 없어요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (52, "기업가정신은 새로운 것에 도전하고 발전하려는 마음이에요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (53, "기업은 수출을 통해 외화를 벌 수 있어요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (54, "기업은 기술 개발 없이도 경쟁에서 이길 수 있어요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (55, "생산이란 물건이나 서비스를 만들어내는 것이에요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (56, "생산성은 노력에 비해 얼마나 많이 만들 수 있는지를 나타내요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (57, "생산에는 땅, 사람, 돈, 경영능력이 필요해요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (58, "생산성이 낮을수록 기업의 경쟁력이 높아져요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (59, "생산성이 높으면 같은 시간에 더 많은 것을 만들 수 있어요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (60, "국민소득이란 한 나라의 국민이 1년 동안 만든 모든 것을 돈으로 계산한 것이에요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (61, "GDP는 우리나라 기업이 해외에서 번 돈을 의미해요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (62, "GNP는 우리 국민이 만든 가치를 기준으로 해요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (63, "국민소득이 많아지면 나라 경제가 성장하고 있다는 뜻이에요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (64, "경제성장은 나라가 점점 가난해지는 것을 뜻해요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (65, "한 나라 국민이 1년간 생산한 것을 돈으로 나타낸 것이 국민소득이에요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (66, "GDP는 국내에서 생산된 것을, GNP는 우리 국민이 만든 것을 의미해요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (67, "국민소득이 줄어들수록 경제가 성장해요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (68, "경제성장은 국민소득이 점점 많아지는 것을 뜻해요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (69, "국민소득은 경제와 관계없는 지표예요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (70, "실업은 일할 수 있지만 일자리가 없는 상태를 말해요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (71, "실업자가 많아지면 가정경제에 영향이 없어요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (72, "실업은 나라 경제에도 부정적인 영향을 줘요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (73, "정부는 일자리를 늘리기 위한 정책을 펼쳐요.", "O", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (74, "실업은 개인 문제일 뿐, 사회에는 영향을 주지 않아요.", "X", NULL, "3");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (75, "시장경제는 개인과 기업이 자유롭게 경쟁하는 경제 시스템이에요.", "O", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (76, "정부는 공정한 경쟁을 도와주는 역할을 해요.", "O", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (77, "도로, 공원 같은 시설은 정부가 만들고 관리해요.", "O", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (78, "시장경제에서는 정부의 역할이 필요 없어요.", "X", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (79, "정부는 모두가 안전하고 행복하게 살 수 있도록 도와줘요.", "O", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (80, "세금은 나라가 하는 일에 필요한 돈을 국민에게 걷는 것이에요.", "O", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (81, "직접세는 물건을 살 때 내는 세금이에요.", "X", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (82, "정부는 세금으로 학교, 병원, 도로 등을 만들어요.", "O", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (83, "세금은 오직 부자만 내요.", "X", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (84, "세금은 나라에 꼭 필요한 일을 하는 데 사용돼요.", "O", NULL, "4");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (85, "주식은 회사를 작게 나눈 조각이에요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (86, "주식을 사면 그 회사의 일부 주인이 돼요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (87, "회사는 돈이 필요할 때 주식을 팔 수 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (88, "주식을 사도 회사와는 아무런 관계가 없어요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (89, "회사가 잘되면 주식 가격이 오르거나 배당금을 받을 수 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (90, "주식을 싸게 사서 비쌀 때 팔면 이익을 얻을 수 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (91, "주식은 항상 가격이 올라요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (92, "주식 투자에는 신중한 판단이 필요해요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (93, "주식 투자는 전혀 위험하지 않아요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (94, "차익이란 주식을 팔아 얻는 이익이에요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (95, "주가는 주식 한 조각의 가격이에요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (96, "매수는 주식을 파는 것이에요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (97, "배당금은 회사가 잘됐을 때 주인에게 주는 돈이에요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (98, "차트는 주식 가격의 흐름을 그림으로 나타낸 것이에요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (99, "리스크는 반드시 수익을 뜻하는 말이에요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (100, "주식을 사는 이유는 회사가 잘될 것 같아서일 수 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (101, "주식을 파는 이유는 회사에 좋은 소식이 있을 때예요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (102, "배당금을 받기 위해 주식을 사기도 해요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (103, "주식을 파는 이유 중 하나는 주식 가격이 올랐을 때예요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (104, "다른 회사 주식을 사기 위해 기존 주식을 팔기도 해요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (105, "주식은 항상 돈을 벌 수 있는 안전한 방법이에요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (106, "회사가 손해를 보면 주식 가격이 떨어질 수 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (107, "잘 모르는 주식을 따라 사면 손해 볼 수 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (108, "너무 욕심을 부리면 손해를 볼 수도 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (109, "리스크를 알면 더 신중한 판단을 할 수 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (110, "인기 제품이 출시되면 주가가 오를 수 있어요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (111, "좋은 뉴스가 나올 때는 주가가 내려가요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (112, "사람들이 많이 팔면 주가가 내려가요.", "O", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (113, "경쟁사가 더 잘 나가면 주가가 오를 수 있어요.", "X", NULL, "5");
INSERT INTO quiz (id, question, answer, explanation, level) VALUES (114, "정치나 전쟁 같은 나쁜 뉴스는 주가에 영향을 줄 수 있어요.", "O", NULL, "5");
